### ISSUE TITLE
yaml value converted to string parameter

### ISSUE THREAD

**Issue by christianrauch** [ros2/rclcpp#1905]
## Bug report

A yaml structure that is set as parameter value is stored as string.

**Required Info:**

- Operating System: Ubuntu 20.04
- Installation type: binaries
- Version or commit hash: galactic
- Client library (if applicable): rclcpp

#### Steps to reproduce issue

1. declare a parameter `this->declare_parameter("bla");`, e.g. in the `set_and_get_parameters` demo example
2. run node: `ros2 run demo_nodes_cpp set_and_get_parameters`
3. create a configuration file `cfg.yaml`:
```yaml
/set_and_get_parameters:
  ros__parameters:
    bla:
    - x: 23
      y: 45
    - x: 55
      y: 123
```
4. `ros2 param load set_and_get_parameters cfg.yaml`
5. verify value: `ros2 param get set_and_get_parameters bla`

#### Expected behavior
The yaml structure should be properly represented as a list of dicts. The same goes for "arrays of arrays":
```yaml
bla:
- [23,45]
- [55,123]
```
which are also represented as a string.

#### Actual behavior
The value is interpreted as ordinary string: `String value is`
